### ISSUE TITLE
Hola, ¿qué hace este repo?

### ISSUE THREAD

**Issue by javiermurillo** [picharras/conekta#1]
Hola @picharras, me gustaría saber qué hace este repo y si es útil para agregar al repo de conekta-examples https://github.com/conekta-examples. En caso de que sea algo de utilidad puedes agregar un README y me avisas para hacer el fork. 

Gracias :smile:

**Comment by picharras** [comment]
Contiene ejemplos de integración de las herramientas de conekta en varios lenguajes. Creo que si sería adecuando algún readme

**Comment by javiermurillo** [comment]
Venga! Ojalá y pronto pueda leer ese README  :smile: :beers:
